'use client';
import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import Link from 'next/link';
import { compensationTypes, recruitmentRoles } from '../../lib/recruitment';
import './recruitment.css';
import RecruitmentPrivateFields,{emptyPrivate,type PrivateDraft} from './RecruitmentPrivateFields';
import RecruitmentApplications from './RecruitmentApplications';
import RecruitmentLinks from './RecruitmentLinks';
import {readContacts} from '../../lib/recruitment-private';

type Post = {id:string; title:string; body:string; tags:string[]; compensation:string; schedule:string; status:string; display_name:string; profile_handle:string|null; created_at:string; contact_url?:string; intro_urls?:string[]|null; mine:boolean};
type Alert = {id:string; post_id:string; matched_keywords:string[]; read_at:string|null; recruitment_posts:{title:string;status:string}|null};
type Board = {signedIn:boolean; posts:Post[]; hasMore:boolean; keywords:string[]; notifications:Alert[]; unread:number};
const initial:Board = {signedIn:false,posts:[],hasMore:false,keywords:[],notifications:[],unread:0};
function Bell() {return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M9 21h6"/></svg>;}
export default function RecruitmentBoard() {
 const [data,setData]=useState(initial), [loading,setLoading]=useState(true), [error,setError]=useState(''), [notice,setNotice]=useState('');
 const [page,setPage]=useState(0), [tag,setTag]=useState(''), [view,setView]=useState<'posts'|'alerts'>('posts');
 const [editing,setEditing]=useState(false), [keywordsOpen,setKeywordsOpen]=useState(false), [keywords,setKeywords]=useState('');
 const [busy,setBusy]=useState(false), [selected,setSelected]=useState<Post|null>(null), [roles,setRoles]=useState<string[]>([]);
 const [editPost,setEditPost]=useState<Post|null>(null);
 const [privateDraft,setPrivateDraft]=useState<PrivateDraft>(emptyPrivate),[privateLoading,setPrivateLoading]=useState(false),[uploading,setUploading]=useState(false),[privateError,setPrivateError]=useState(false);
 const [introLinks,setIntroLinks]=useState<string[]>(['']);
 const editSequence=useRef(0);
 const sequence=useRef(0), keywordLock=useRef(false);
 const openCompose=async(post:Post|null=null)=>{const seq=++editSequence.current;setSelected(null);setEditPost(post);setRoles(post?.tags||[]);setPrivateDraft(emptyPrivate);setIntroLinks(post?.intro_urls?.length?post.intro_urls:[post?.contact_url||'']);setPrivateError(false);setEditing(true);setNotice('');setPrivateLoading(!!post);requestAnimationFrame(()=>document.getElementById('guild-board')?.scrollIntoView({behavior:'smooth',block:'start'}));
 if(post)try{const r=await fetch('/api/community/applications?post='+post.id,{cache:'no-store'});const j=await r.json();if(!r.ok||!j.mine)throw Error(j.error||'수정 권한이 없습니다.');if(seq===editSequence.current)setPrivateDraft({contacts:readContacts(j.author||{}),files:j.author?.files||[]});}catch(e){if(seq===editSequence.current){setPrivateError(true);setNotice(e instanceof Error?e.message:'자료를 불러오지 못했습니다.');}}finally{if(seq===editSequence.current)setPrivateLoading(false);}};
 const load=useCallback(async (quiet=false) => {
  const seq=++sequence.current; if(!quiet) setLoading(true);
  try {const response=await fetch(`/api/community?page=${page}&tag=${encodeURIComponent(tag)}`,{cache:'no-store'}); const result=await response.json(); if(!response.ok) throw new Error(result.error); if(seq===sequence.current){setData(result);setError('');}}
  catch(e){if(seq===sequence.current)setError(e instanceof Error?e.message:'게시판을 불러오지 못했습니다.');}
  finally {if(seq===sequence.current)setLoading(false);}
 },[page,tag]);
 useEffect(()=>{const start=setTimeout(()=>void load(),0);const timer=setInterval(()=>{if(document.visibilityState==='visible')void load(true);},60000);const focus=()=>void load(true);window.addEventListener('focus',focus);return()=>{clearTimeout(start);clearInterval(timer);window.removeEventListener('focus',focus);};},[load]);
 const mutate=async(body:Record<string,unknown>)=>{
  setBusy(true);setNotice('');
  try{const r=await fetch('/api/community',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error);await load(true);return true;}
  catch(e){setNotice(e instanceof Error?e.message:'저장에 실패했습니다. 다시 시도해 주세요.');return false;}finally{setBusy(false);}
 };
 const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await mutate({action:editPost?'edit':'create',id:editPost?.id,title:f.get('title'),body:f.get('body'),schedule:f.get('schedule'),contact:introLinks[0],introLinks,compensation:f.get('compensation'),tags:roles,privateDetails:{contacts:privateDraft.contacts,fileIds:privateDraft.files.map(f=>f.id)},privacyConsent:f.get('privacyConsent')==='on'})){setEditing(false);setRoles([]);setNotice('');setEditPost(null);setView('posts');setPage(0);setTag('');}};
 const saveKeywords=async(next:string[])=>{if(keywordLock.current)return false;keywordLock.current=true;try{return await mutate({action:'keywords',keywords:next});}finally{keywordLock.current=false;}};
 const commitKeyword=async()=>{const incoming=keywords.split(',').map(v=>v.trim().toLowerCase()).filter(Boolean);if(!incoming.length||keywordLock.current)return;const next=[...new Set([...data.keywords,...incoming])];if(next.length>8||next.some(v=>v.length>24)){setNotice('키워드는 각 24자, 최대 8개입니다.');return;}if(await saveKeywords(next)){setKeywords('');setNotice('관심 키워드가 자동 저장되었습니다.');}};
 const keywordChips=<div className="guild-keyword-chips">{data.keywords.map(k=><span key={k}>{k}<button type="button" aria-label={k+' 키워드 삭제'} disabled={busy} onClick={()=>void saveKeywords(data.keywords.filter(v=>v!==k))}>×</button></span>)}</div>;
 const visiblePosts=selected&&!data.posts.some(p=>p.id===selected.id)?[selected,...data.posts]:data.posts;
 const login=<Link href="/login?next=%2Fcommunity">로그인하기 ↗</Link>;
 const openAlert=async(alert:Alert)=>{
  if(!await mutate({action:'read',id:alert.id}))return;
  try{const response=await fetch(`/api/community/post?id=${alert.post_id}`,{cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result.error);setSelected(result.post);setView('posts');setTag('');setPage(0);}
  catch(e){setNotice(e instanceof Error?e.message:'모집글을 불러오지 못했습니다. 다시 시도해 주세요.');}
 };
 return <section className="guild" aria-label="함께 만들 사람 찾기">
  <header className="guild-hero">
   <div className="guild-hero-copy"><p className="guild-eyebrow">BOTTOPIA · CREATOR GUILD</p><h1>혼자 시작한 아이디어,<br/><em>함께 완성하세요.</em></h1><p className="guild-intro">영상, 음악, 이야기.<br className="guild-mobile-break"/> 서로의 작업에 필요한 동료를 만나세요.</p><div className="guild-hero-actions">{data.signedIn?<button className="guild-primary" onClick={()=>openCompose()}><span aria-hidden="true">🙋</span> 함께할 사람 찾기</button>:<Link className="guild-primary" href="/login?next=%2Fcommunity">🙋 로그인하고 모집하기</Link>}<button className="guild-hero-link" onClick={()=>{setEditing(false);setView('posts');requestAnimationFrame(()=>document.getElementById('guild-board')?.scrollIntoView({behavior:'smooth',block:'start'}));}}>모집글 둘러보기</button></div></div>
   <span className="guild-hall-caption" aria-hidden="true">A PLACE TO MEET. A WORLD TO MAKE.</span>
  </header>
  <div className="guild-body guild-split" id="guild-board"><div className="guild-content">
   <div className="guild-heading"><div><p className="guild-eyebrow">FIND YOUR PEOPLE</p><h2>{editing?(editPost?'모집글 수정':'함께할 사람 찾기'):'모집글 둘러보기'}</h2></div></div>
   {notice&&<p className="guild-notice" role="status">{notice}</p>}
   {editing&&<form className="guild-compose" id="guild-compose" onSubmit={create}><div className="guild-heading"><h3>{editPost?'모집글 수정':'어떤 작업을 함께할까요?'}</h3><button type="button" className="guild-text-button" onClick={()=>{setEditing(false);setView('posts');}}>목록으로</button></div><label>모집 제목<input name="title" defaultValue={editPost?.title} required minLength={4} maxLength={80} placeholder="1분 단편에 음악을 더해주실 분을 찾아요"/></label><label>내용<textarea name="body" defaultValue={editPost?.body} required minLength={20} maxLength={2000} rows={4} placeholder="만들고 있는 작업과 내가 맡은 역할, 함께할 분에게 바라는 점을 알려주세요. (20자 이상)"/></label><fieldset><legend>필요한 역할 <span>여러 개 선택 가능</span></legend><div className="guild-chips">{recruitmentRoles.map(role=><button type="button" key={role} aria-pressed={roles.includes(role)} onClick={()=>setRoles(prev=>prev.includes(role)?prev.filter(v=>v!==role):[...prev,role])}>{role}</button>)}</div></fieldset><div className="guild-form-grid"><label>협업 조건<select name="compensation" defaultValue={editPost?.compensation}>{compensationTypes.map(v=><option key={v}>{v}</option>)}</select></label><label>완료 예정일<input name="schedule" type="date" defaultValue={/^\d{4}-\d{2}-\d{2}$/.test(editPost?.schedule||'')?editPost?.schedule:''} required/>{editPost?.schedule&&!/^\d{4}-\d{2}-\d{2}$/.test(editPost.schedule)&&<small className="guild-help">기존 일정: {editPost.schedule} · 날짜를 선택하세요.</small>}</label></div><RecruitmentLinks value={introLinks} onChange={setIntroLinks}/><p className="guild-help">소개와 닉네임은 공개됩니다. 소개 링크에는 작품·프로필 주소를 입력하세요. 전화번호·이메일·카카오톡 ID는 본문이나 링크에 넣지 마세요.</p>{privateLoading?<p role="status">비공개 자료를 불러오는 중…</p>:privateError?<p role="alert">자료를 불러오지 못해 저장을 막았습니다. 목록으로 돌아간 뒤 다시 수정해 주세요.</p>:<RecruitmentPrivateFields key={editPost?.id||'new'} value={privateDraft} onChange={setPrivateDraft} onBusy={setUploading}/>}<button className="guild-primary" disabled={busy||roles.length===0||privateLoading||privateError||uploading}>{busy?'저장 중…':editPost?'수정 저장':'모집글 등록하기'}</button></form>}
   {!editing&&<section aria-label="모집 목록">
   {view==='alerts'&&<><p className="guild-help">내 관심 키워드</p>{keywordChips}</>}
   <nav className="guild-tabs" aria-label="모집 게시판 보기"><button aria-pressed={view==='posts'} onClick={()=>setView('posts')}>모집 게시판</button><button aria-pressed={view==='alerts'} onClick={()=>setView('alerts')}><Bell/> 내 알림 {data.unread>0&&<span className="guild-count">{data.unread}</span>}</button></nav>
   {error?<div className="guild-empty" role="alert"><p>{error}</p><button className="guild-outline" onClick={()=>void load()}>다시 불러오기</button></div>:loading?<p className="guild-empty" role="status">모집 소식을 불러오는 중…</p>:view==='posts'?<>
    <div className="guild-chips guild-filters" aria-label="역할별 모집글">{['전체',...recruitmentRoles].map(role=><button key={role} aria-pressed={tag===(role==='전체'?'':role)} onClick={()=>{setTag(role==='전체'?'':role);setPage(0);}}>{role}</button>)}</div>
    {visiblePosts.length?<div className="guild-posts">{visiblePosts.map(post=><article className={`guild-card ${selected?.id===post.id?'is-expanded':''}`} key={post.id}>{post.mine&&<button className="guild-card-delete" aria-label={`${post.title} 삭제`} disabled={busy} onClick={async()=>{if(window.confirm('이 모집글을 삭제할까요? 삭제 후 복구할 수 없습니다.')&&await mutate({action:'delete',id:post.id})){if(selected?.id===post.id)setSelected(null);setNotice('모집글을 삭제했습니다.');}}}>×</button>}<div className="guild-card-top"><span className={post.status==='open'?'guild-open':'guild-closed'}>{post.status==='open'?'모집 중':'모집 마감'}</span><span>{post.compensation}</span></div><h3><button onClick={()=>setSelected(selected?.id===post.id?null:post)}>{post.title}</button></h3><p className={selected?.id===post.id?'guild-detail-body':'guild-excerpt'}>{post.body}</p><div className="guild-tags">{post.tags.map(t=><span key={t}>#{t}</span>)}</div><footer><span>{post.display_name} · {new Date(post.created_at).toLocaleDateString('ko-KR')}</span><div className="guild-card-actions">{post.mine&&<button className="guild-text-button" onClick={()=>openCompose(post)}>수정</button>}<button className="guild-text-button" aria-expanded={selected?.id===post.id} onClick={()=>setSelected(selected?.id===post.id?null:post)} aria-label={`${post.title} 모집 내용 보기`}>{selected?.id===post.id?'접기 −':'자세히 +'}</button></div></footer>{selected?.id===post.id&&<div className="guild-card-detail"><dl><dt>협업 조건</dt><dd>{post.compensation}</dd><dt>일정</dt><dd>{post.schedule}</dd><dt>작성자</dt><dd>{post.profile_handle?<Link href={`/creators/${encodeURIComponent(post.profile_handle)}`}>{post.display_name} ↗</Link>:post.display_name}</dd></dl><div className="guild-public-links">{(post.intro_urls?.length?post.intro_urls:post.contact_url?[post.contact_url]:[]).map((url,i)=><a key={url} href={url} target="_blank" rel="noopener noreferrer nofollow">작성자 소개 링크 {i+1} ↗</a>)}</div><p className="guild-help">소개 링크는 작성자가 등록한 외부 페이지입니다.</p>{data.signedIn?<RecruitmentApplications key={post.id} postId={post.id}/>:<p className="guild-help">지원하려면 로그인하세요.</p>}{post.mine&&post.status==='open'&&<button className="guild-outline" disabled={busy} onClick={async()=>{if(await mutate({action:'close',id:post.id}))setSelected({...post,status:'closed'});}}>모집 마감하기</button>}</div>}</article>)}</div>:<div className="guild-empty"><span className="guild-empty-symbol" aria-hidden="true">✧</span><h3>{tag?'아직 이 역할을 찾는 모집글이 없어요.':'첫 번째 동료를 기다리고 있어요.'}</h3><p>“저는 이런 작업을 하고 있어요. 같이 만들래요?”<br/>짧은 소개로 새로운 협업을 시작해 보세요.</p></div>}
    {(page>0||data.hasMore)&&<div className="guild-pagination"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>이전</button><span>{page+1} 페이지</span><button disabled={!data.hasMore} onClick={()=>setPage(p=>p+1)}>다음</button></div>}
   </>:!data.signedIn?<div className="guild-empty"><p>로그인하면 관심 키워드 알림을 받을 수 있습니다.</p>{login}</div>:<div className="guild-alerts">{data.notifications.length?data.notifications.map(a=><article key={a.id} className={a.read_at?'':'is-unread'}><div><span className="guild-tags">{a.matched_keywords.map(k=>`#${k}`).join(' ')}</span><h3>{a.recruitment_posts?.title||'삭제된 모집글'}</h3><p>{a.recruitment_posts?.status==='closed'?'모집이 마감되었습니다.':'관심 키워드와 일치하는 모집글입니다.'}</p></div><button className="guild-outline" disabled={busy} onClick={()=>void openAlert(a)}>내용 보기</button></article>):<div className="guild-empty"><h3>아직 도착한 알림이 없어요.</h3><p>관심 키워드를 저장하면 새로운 모집 소식을 이곳에서 확인할 수 있어요.</p></div>}</div>}
   </section>}
  </div><div className="guild-keyword-control"><button className="guild-outline" onClick={()=>{setKeywordsOpen(!keywordsOpen);}} aria-expanded={keywordsOpen} aria-controls="guild-keyword-panel"><Bell/> 관심 키워드 설정</button>
   {keywordsOpen&&<section id="guild-keyword-panel" className="guild-settings" aria-label="관심 키워드 알림 설정">{data.signedIn?<><label htmlFor="guild-keywords">관심 키워드<input id="guild-keywords" value={keywords} disabled={busy} onChange={e=>setKeywords(e.target.value)} onBlur={()=>void commitKeyword()} onKeyDown={e=>{if(!e.nativeEvent.isComposing&&(e.key==='Enter'||e.key===',')){e.preventDefault();void commitKeyword();}}} placeholder="예: 음악, 단편, 세계관" maxLength={210}/></label>{keywordChips}<small>Enter·쉼표 또는 입력칸을 벗어나면 저장됩니다.<br/>최대 8개 · 새 모집글은 내 알림에서 확인</small></>:login}</section>}</div>
  </div>

 </section>;
}
