// Source-linked research, never uploaded or attributed to BOTTOPIA as original work.
export type VideoReference = {
  id:string; title:string; summary:string; category:string; tool:string; model:string;
  durationSeconds:15|30; author:string; sourceUrl:string; publishedAt:string|null;
  region:'국내'|'해외'; evidence:string; prompt:string;
};
export const videoReferences: VideoReference[] = [
  {id:'seedance-grwm',title:'출근 준비, 스마트폰 원테이크',summary:'방 안에서 준비하고 문을 나서는 30초 셀피 브이로그.',category:'LIFESTYLE',tool:'Seedance',model:'Seedance 2.5',durationSeconds:30,author:'u/Livid_Necessary_Real',region:'해외',publishedAt:'2026-10-08',sourceUrl:'https://www.reddit.com/r/seedance2pro/comments/1x0bfb3/i_made_a_30second_get_ready_with_me_vlog_using/',evidence:'게시자가 모델·30초 길이와 전체 프롬프트를 공개. 영상 파일의 실측 길이는 미확인.',prompt:'30초, 9:16 스마트폰 셀피 원테이크. 동일한 성인 인물이 휴대전화를 한 손으로 들고 아침 준비를 한다. 0–6초: 창가의 침실에서 잠이 덜 깬 표정으로 카메라를 보며 오늘 일정에 대해 짧게 말한다. 6–15초: 거울을 확인하고 머리를 정리한다. 손에 든 휴대전화는 바뀌지 않는다. 15–24초: 겉옷을 고르고 가방을 챙겨 문으로 걸어간다. 24–30초: 카메라에 짧게 인사하고 프레임이 자연스럽게 내려간다. 창문 자연광, 작은 손떨림, 방 안의 생활 소리. 음악·미용 필터·자막·새 휴대전화 생성 없음. 얼굴·머리·방의 배치를 유지한다.'},
  {id:'promptwhat-talking-head',title:'말하는 영상과 키네틱 타이포',summary:'씨댄스 영상 위에 코드로 글자와 카드 모션을 합성한 국내 사례.',category:'EXPERIMENT',tool:'Seedance + Claude Code',model:'Seedance 2.5',durationSeconds:30,author:'Prompt_what (@Promptwhat)',region:'국내',publishedAt:'2026-10-02',sourceUrl:'https://x.com/Promptwhat/status/2106006916665372872',evidence:'원문에서 씨댄스 2.5 한 번에 30초 생성 확인. 게시된 편집본은 브라우저 실측 29.708초. 자막 효과는 Claude Code 후편집이며 모델 자체 효과가 아님.',prompt:'30초, 밝은 실내의 토킹헤드 영상. 성인 발표자가 작은 마이크를 들고 정면 카메라에 편집 작업에 대해 한국어로 말한다. 0–8초: 문제를 짧게 설명한다. 8–20초: 자신이 시도한 방법을 설명하며 작은 손동작을 한다. 20–30초: 결과를 정리하고 카메라를 보며 마무리한다. 동일한 얼굴·의상·마이크, 안정된 상반신 구도, 커튼을 통과하는 부드러운 자연광, 선명한 대사, 음악과 화면 글자 없음. 생성 후 별도 편집: 인물 마스크를 만들고 원본 영상 / 큰 글자 / 인물 전경의 세 레이어를 겹친다. 대사 타이밍에 정보 카드와 타이핑 애니메이션을 추가한다.'},
  {id:'hailuo-performance',title:'두 사람의 무대 퍼포먼스',summary:'레퍼런스 영상의 동작을 유지하는 15초 영상 변환 사례.',category:'MUSIC',tool:'Hailuo',model:'MiniMax Hailuo 3',durationSeconds:15,author:'arelion.dev',region:'해외',publishedAt:'2026-09-24',sourceUrl:'https://arelion.dev/case-studies/hotel-lobby-ai-video/',evidence:'제작자가 15초 결과 영상과 제작 방식을 공개. 실존 인물 패러디·기존 공연 음악을 사용한 사례이므로 재사용 권리가 확인된 자료만 별도로 준비해야 함.',prompt:'15초, 16:9 무대 퍼포먼스. 사용 권리가 확보된 두 성인 캐릭터 사진과 직접 제작한 공연 동작 레퍼런스를 사용한다. 왼쪽 인물과 오른쪽 인물의 얼굴·의상을 각각 고정한다. 레퍼런스의 카메라 위치, 동작 타이밍, 무대 배치와 컷 흐름을 유지하면서 인물만 지정한 캐릭터로 바꾼다. 얼굴이 서로 섞이지 않도록 한다. 조명과 손동작을 안정적으로 유지한다. 음원은 사용 권리가 확보된 곡으로 후편집하고 영상 프레임레이트에 맞춰 동기화한다. 타인의 로고나 워터마크를 제거하지 않는다.'},
  {id:'seedance-party-pool',title:'실내 파티에서 수영장까지',summary:'장소·조명·소품의 연속성을 시험하는 30초 롱테이크.',category:'LIFESTYLE',tool:'Seedance',model:'Seedance 2.5',durationSeconds:30,author:'u/Fresh-Resolution182',region:'해외',publishedAt:null,sourceUrl:'https://www.reddit.com/r/Seedance_AI/comments/1vg13x1/seedance_25_handled_this_30s_singletake/',evidence:'게시자가 모델·30초 원테이크와 타임라인 프롬프트를 공개. 정확한 게시 날짜와 파일 실측 길이는 미확인.',prompt:'30초, 한 번도 끊기지 않는 핸드헬드 숏. 성인 주인공이 낮의 실내 파티에서 정원을 지나 수영장으로 이동한다. 0–5초: 소파에서 일어나 빈손으로 테이블에 다가간다. 5–10초: 음료 한 잔을 받아 사람들 사이로 걷는다. 10–16초: 유리문을 지나 정원으로 나오며 카메라가 측면으로 돈다. 16–22초: 컵을 실제 테이블 위에 놓고 수영장으로 걸어간다. 22–27초: 물에 뛰어들고 카메라가 물 표면 가까이 따라간다. 27–30초: 수면 위로 올라와 웃는 얼굴과 정원의 전경으로 끝낸다. 성인 인물만 등장. 동일한 얼굴·머리·수영복·소품을 유지하고 실내에서 실외로 노출이 자연스럽게 변한다. 순간이동·하드컷·자막 없음.'},
  {id:'kling-korean-dialogue',title:'한국어 대화와 숏·리버스숏',summary:'첫 프레임에서 와이드와 클로즈업으로 이어지는 15초 대화 장면.',category:'DRAMA',tool:'Kling',model:'Kling 3.0',durationSeconds:15,author:'Matt Workman',region:'해외',publishedAt:null,sourceUrl:'https://www.linkedin.com/posts/mattworkman_with-new-ai-models-its-hard-to-market-nuance-activity-7425175011222503424-XPVt',evidence:'제작자가 단일 15초 Kling 3.0 Multi Shot과 한국어 버전이라고 명시. 자막은 후편집. 정확한 게시 날짜와 파일 실측 길이는 미확인.',prompt:'15초, 한국어 대화 드라마, 멀티숏. 성인 두 인물의 첫 프레임을 공간과 인물 레퍼런스로 사용한다. 숏1 0–5초: 두 인물의 위치 관계가 보이는 와이드 숏, 한 인물이 다가와 멈춘다. 숏2 5–10초: 첫 인물의 미디엄 클로즈업, “오늘은 이야기할 수 있어?”라고 조심스럽게 말한다. 숏3 10–15초: 상대의 리버스 클로즈업, 잠시 숨을 고른 뒤 “응, 나도 기다렸어.”라고 답한다. 180도 축과 시선 방향을 유지한다. 자연스러운 한국어 립싱크, 한 번에 한 명만 말함, 걸음 소리와 실내 룸톤, 음악·자막 없음.'},
  {id:'kling-subtle-performance',title:'어색한 순간의 미세한 연기',summary:'대사보다 표정과 잠깐의 침묵에 집중한 15초 멀티숏.',category:'DRAMA',tool:'Kling',model:'Kling 3.0',durationSeconds:15,author:'Billy Boman',region:'해외',publishedAt:null,sourceUrl:'https://www.linkedin.com/posts/billyboman_kling-30-is-absolutely-bonkers-this-activity-7425258978022068224-_6ng',evidence:'제작자가 단일 이미지에서 생성한 15초 Kling 3.0 Multicam이라고 명시. 정확한 게시 날짜와 파일 실측 길이는 미확인.',prompt:'15초, 성인 두 사람의 절제된 대화 장면. 0–4초: 같은 공간의 투숏, 한 인물이 말을 꺼내기 전에 눈을 피한다. 4–9초: 첫 인물의 클로즈업, “이렇게 함께 있는 시간이 좋아.”라고 낮게 말한 뒤 작은 미소를 짓는다. 9–15초: 상대의 리버스숏, 잠깐 침묵하고 어색하게 머리를 만지며 “나도 그래.”라고 답한다. 얼굴·의상·좌석과 시선 방향을 유지한다. 과장되지 않은 표정, 실제 대화 같은 호흡과 간격, 자연스러운 핸드헬드, 또렷한 목소리, 배경 음악·자막 없음.'},
];
export function latestReferences(items: VideoReference[]): VideoReference[] {
  return [...items].sort((a,b)=>(b.publishedAt ? Date.parse(b.publishedAt):0)-(a.publishedAt ? Date.parse(a.publishedAt):0));
}
